[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
name = "pallet-xcm"
version = "0.9.12"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.130", optional = true, features = ["derive"] }
log = { version = "0.4.14", default-features = false }

sp-std = { git = "https://github.com/mustermeiszer/substrate", default-features = false, branch = "polkadot-v0.9.12" }
sp-runtime = { git = "https://github.com/mustermeiszer/substrate", default-features = false, branch = "polkadot-v0.9.12" }
sp-core = { git = "https://github.com/mustermeiszer/substrate", default-features = false, branch = "polkadot-v0.9.12" }
frame-support = { git = "https://github.com/mustermeiszer/substrate", default-features = false, branch = "polkadot-v0.9.12" }
frame-system = { git = "https://github.com/mustermeiszer/substrate", default-features = false, branch = "polkadot-v0.9.12" }

xcm = { path = "..", default-features = false }
xcm-executor = { path = "../xcm-executor", default-features = false }

[dev-dependencies]
pallet-balances = { git = "https://github.com/mustermeiszer/substrate", branch = "polkadot-v0.9.12" }
polkadot-runtime-parachains = { path = "../../runtime/parachains" }
sp-io = { git = "https://github.com/mustermeiszer/substrate", default-features = false , branch = "polkadot-v0.9.12" }
xcm-builder = { path = "../xcm-builder" }
polkadot-parachain = { path = "../../parachain" }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"serde",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"xcm/std",
]
runtime-benchmarks = []
